import { randomUUID } from 'node:crypto'
import { createServer, type Socket } from 'node:net'

// Queue for H.264 NALUs waiting to be sent to connected clients
const frameQueue: Buffer[] = []
const maxQueueSize = 10

// Connected RTSP sessions
interface RtspSession {
  socket: Socket
  sessionId: string
  cseq: number
  state: 'idle' | 'setup' | 'playing'
  rtpSeq: number
  rtpTimestamp: number
  lastTimestamp: number
}

const sessions = new Map<string, RtspSession>()

// H.264 SPS/PPS for baseline profile 1920x1080
// These are generated by x264 and needed in SDP
const SPS = Buffer.from([
  0x67, 0x42, 0xc0, 0x28, 0xd9, 0x00, 0x78, 0x02, 0x27, 0x65, 0x84, 0x00, 0x00, 0x03, 0x00, 0x04,
  0x00, 0x00, 0x03, 0x00, 0xf0, 0x3c, 0x64, 0xa3, 0xc0,
])

const PPS = Buffer.from([0x68, 0xce, 0x3c, 0x80])

function buildSdp(rtspPort: number): string {
  const host = process.env.ONVIF_HOST ?? '127.0.0.1'
  const sdp = [
    'v=0',
    'o=- 0 0 IN IP4 127.0.0.1',
    's=Weather Dashboard Stream',
    'c=IN IP4 127.0.0.1',
    't=0 0',
    'a=control:*',
    'm=video 0 RTP/AVP 96',
    'a=rtpmap:96 H264/90000',
    'a=fmtp:96 profile-level-id=42c028;packetization-mode=1;sprop-parameter-sets=' +
      `${Buffer.from(SPS.subarray(1)).toString('base64').replace(/=/g, '')},${Buffer.from(PPS.subarray(1)).toString('base64').replace(/=/g, '')}`,
    'a=control:trackID=1',
  ]
  return sdp.join('\r\n') + '\r\n'
}

// RTP timestamp clock rate for H.264
const RTP_CLOCK_RATE = 90_000
// Timestamp increment per frame at given framerate
const FRAME_DURATION_US = 1_000_000 / 5 // 5fps

// Build RTP packet from H.264 NALU
function buildRtpPacket(nalu: Buffer, seq: number, timestamp: number, ssrc: number): Buffer {
  // RTP header: 12 bytes
  // Version(2) + Padding(0) + Extension(0) + CC(0) | Marker(1) | PayloadType(96)
  // Sequence Number (2 bytes)
  // Timestamp (4 bytes)
  // SSRC (4 bytes)

  const naluData = nalu.subarray(4) // Strip start code
  const rtpPayloadSize = naluData.length

  // For large NALUs, we'd need fragmentation (FU-A), but at 1920x1080 with ultrafast preset,
  // most frames fit in a single RTP packet. We'll do single-NALU mode for simplicity.
  // If the NALU is too large for a single packet (>1400 bytes), fragment it.

  const rtpHeader = Buffer.alloc(12)
  rtpHeader.writeUInt8(0x80, 0) // Version 2, marker bit
  rtpHeader.writeUInt8(0x60, 1) // Payload type 96
  rtpHeader.writeUInt16BE(seq, 2) // Sequence number
  rtpHeader.writeUInt32BE(timestamp, 4) // Timestamp
  rtpHeader.writeUInt32BE(ssrc, 8) // SSRC

  // Interleaved RTP format: $ + channel(1 byte) + length(2 bytes big-endian) + data
  const channel = 0 // Channel 0 for RTP
  const totalLength = rtpHeader.length + rtpPayloadSize
  const interleavedHeader = Buffer.alloc(4)
  interleavedHeader.writeUInt8(0x24, 0) // '$'
  interleavedHeader.writeUInt8(channel, 1)
  interleavedHeader.writeUInt16BE(totalLength, 2)

  return Buffer.concat([interleavedHeader, rtpHeader, naluData])
}

// Fragment large NALUs using FU-A method
function fragmentNalu(nalu: Buffer, maxPayloadSize: number): Buffer[] {
  const naluData = nalu.subarray(4) // Strip start code
  const fragments: Buffer[] = []

  if (naluData.length <= maxPayloadSize) {
    // Single NALU fits
    fragments.push(nalu)
    return fragments
  }

  // FU-A header: NRI (3 bits) + NAL type 28
  const nalHeader = nalu[3]
  const nri = (nalHeader >> 5) & 0x07
  const fuIndicator = (nri << 5) | 28
  const fuHeader = nalHeader & 0x1f // Original NAL type

  let offset = 0
  const fragmentSize = maxPayloadSize - 2 // 2 bytes for FU headers

  while (offset < naluData.length) {
    const remaining = naluData.length - offset
    const size = Math.min(fragmentSize, remaining)
    const isStart = offset === 0
    const isEnd = offset + size >= naluData.length

    const fuHeaderBuf = Buffer.alloc(2)
    fuHeaderBuf[0] = fuIndicator
    fuHeaderBuf[1] = fuHeader
    if (isStart) fuHeaderBuf[1] |= 0x80 // S bit
    if (isEnd) fuHeaderBuf[1] |= 0x40 // E bit

    const fragmentData = naluData.subarray(offset, offset + size)
    fragments.push(
      Buffer.concat([Buffer.from([0x00, 0x00, 0x00, 0x01]), fuHeaderBuf, fragmentData])
    )
    offset += size
  }

  return fragments
}

function sendFrameToSession(session: RtspSession, nalu: Buffer) {
  if (session.state !== 'playing') return

  const ssrc = parseInt(session.sessionId.slice(0, 8), 16) || 0x12345678
  const maxPayloadSize = 1400 // MTU minus IP/UDP/RTP overhead

  const fragments = fragmentNalu(nalu, maxPayloadSize)

  for (const frag of fragments) {
    const rtpPacket = buildRtpPacket(frag, session.rtpSeq, session.rtpTimestamp, ssrc)
    session.socket.write(rtpPacket)
    session.rtpSeq++
    if (session.rtpSeq > 65535) session.rtpSeq = 0
  }

  session.rtpTimestamp += FRAME_DURATION_US
  if (session.rtpTimestamp > 0xffffffff) session.rtpTimestamp = 0
}

function broadcastFrame(nalu: Buffer) {
  for (const session of sessions.values()) {
    sendFrameToSession(session, nalu)
  }
}

function parseRtspRequest(data: string): {
  method: string
  uri: string
  headers: Record<string, string>
  cseq: number
} {
  const lines = data.split('\r\n')
  const firstLine = lines[0].split(' ')
  const method = firstLine[0]
  const uri = firstLine[1]

  const headers: Record<string, string> = {}
  let cseq = 1

  for (let i = 1; i < lines.length; i++) {
    const [key, ...valueParts] = lines[i].split(':')
    if (key && valueParts.length > 0) {
      headers[key.trim().toLowerCase()] = valueParts.join(':').trim()
    }
    if (key?.trim().toLowerCase() === 'cseq') {
      cseq = parseInt(valueParts.join(':').trim(), 10) || 1
    }
  }

  return { method, uri, headers, cseq }
}

function buildResponse(status: string, cseq: number, extraHeaders: string[] = []): string {
  const headers = [
    `RTSP/1.0 ${status}`,
    `CSeq: ${cseq}`,
    `Date: ${new Date().toUTCString()}`,
    ...extraHeaders,
  ]
  return headers.join('\r\n') + '\r\n\r\n'
}

export interface RtspAuthConfig {
  username: string
  password: string
}

export function startRtspServer(port: number, auth?: RtspAuthConfig) {
  const requireAuth = !!(auth?.username && auth?.password)
  const authUser = auth?.username ?? ''
  const authPass = auth?.password ?? ''

  function verifyAuth(authHeader: string | undefined): boolean {
    if (!authHeader) return false
    const parts = authHeader.split(' ')
    if (parts.length !== 2 || parts[0] !== 'Basic') return false
    const decoded = Buffer.from(parts[1], 'base64').toString('utf-8')
    const [user, pass] = decoded.split(':')
    return user === authUser && pass === authPass
  }
  const server = createServer((socket) => {
    let session: RtspSession | null = null
    let buffer = ''

    socket.on('data', (chunk: Buffer) => {
      buffer += chunk.toString()

      // Check if we have a complete RTSP request (ends with \r\n\r\n)
      const endIndex = buffer.indexOf('\r\n\r\n')
      if (endIndex === -1) return

      const request = buffer.substring(0, endIndex)
      buffer = buffer.substring(endIndex + 4)

      const { method, uri, headers, cseq } = parseRtspRequest(request)

      console.log(`RTSP: ${method} ${uri} (CSeq: ${cseq})`)

      // Require Basic Auth on DESCRIBE/SETUP/PLAY (skip OPTIONS which may not include auth)
      if (requireAuth && !['OPTIONS', 'TEARDOWN'].includes(method)) {
        if (!verifyAuth(headers.authorization)) {
          const response = buildResponse('401 Unauthorized', cseq, [
            'WWW-Authenticate: Basic realm="RTSP Server"',
          ])
          socket.write(response)
          return
        }
      }

      switch (method) {
        case 'OPTIONS': {
          const response = buildResponse('200 OK', cseq, [
            'Public: OPTIONS, DESCRIBE, SETUP, TEARDOWN, PLAY, PAUSE, GET_PARAMETER',
          ])
          socket.write(response)
          break
        }

        case 'DESCRIBE': {
          const sdp = buildSdp(port)
          const response = buildResponse('200 OK', cseq, [
            'Content-Type: application/sdp',
            `Content-Length: ${Buffer.byteLength(sdp)}`,
          ])
          socket.write(response + sdp)
          break
        }

        case 'SETUP': {
          const sessionId = randomUUID().replace(/-/g, '')
          session = {
            socket,
            sessionId,
            cseq,
            state: 'setup',
            rtpSeq: Math.floor(Math.random() * 65535),
            rtpTimestamp: Math.floor(Math.random() * 0xffffffff),
            lastTimestamp: Date.now(),
          }
          sessions.set(sessionId, session)

          const response = buildResponse('200 OK', cseq, [
            `Session: ${sessionId}`,
            'Transport: RTP/AVP/TCP;unicast;interleaved=0-1',
          ])
          socket.write(response)
          break
        }

        case 'PLAY': {
          if (session) {
            session.state = 'playing'
            console.log(`RTSP: Session ${session.sessionId} started playing`)
          }
          const response = buildResponse(
            '200 OK',
            cseq,
            [
              session ? `Session: ${session.sessionId}` : '',
              'RTP-Info: url=rtsp://localhost:554/stream/trackID=1;seq=0;rtptime=0',
            ].filter(Boolean)
          )
          socket.write(response)
          break
        }

        case 'PAUSE': {
          if (session) {
            session.state = 'setup'
          }
          const response = buildResponse(
            '200 OK',
            cseq,
            [session ? `Session: ${session.sessionId}` : ''].filter(Boolean)
          )
          socket.write(response)
          break
        }

        case 'TEARDOWN': {
          if (session) {
            sessions.delete(session.sessionId)
            console.log(`RTSP: Session ${session.sessionId} torn down`)
            session = null
          }
          const response = buildResponse('200 OK', cseq)
          socket.write(response)
          socket.end()
          break
        }

        case 'GET_PARAMETER': {
          const response = buildResponse('200 OK', cseq)
          socket.write(response)
          break
        }

        default: {
          const response = buildResponse('501 Not Implemented', cseq)
          socket.write(response)
        }
      }
    })

    socket.on('error', (err) => {
      console.error('RTSP socket error:', err)
      if (session) {
        sessions.delete(session.sessionId)
      }
    })

    socket.on('close', () => {
      if (session) {
        sessions.delete(session.sessionId)
        console.log(`RTSP: Session ${session.sessionId} closed`)
      }
    })
  })

  server.listen(port, () => {
    console.log(`RTSP server listening on port ${port}`)
  })

  return {
    pushFrame: (nalu: Buffer) => {
      // Keep queue bounded
      if (frameQueue.length >= maxQueueSize) {
        frameQueue.shift()
      }
      frameQueue.push(nalu)

      // Broadcast to all playing sessions
      broadcastFrame(nalu)
    },
    close: () => {
      server.close()
      for (const session of sessions.values()) {
        session.socket.end()
      }
      sessions.clear()
    },
  }
}
